Život tě baví
Gándhí  2016

Orig: D

I:
    D    /F#    G6    A7sus4  A7
    D    /F#    G6    A7sus4  A7
    D    /F#    G6    A7sus4  A7
    B6
    Cadd2

    D       /F#   G6     A7sus4  A7             D       /F#  G6   A7sus4  A7
1.    Rum a sirup s fosforeč     nou              dívku krajinově vděč    nou
    F#mi               Emi                      F#mi          A67sus4  A7  A67      A7
      činí značně nebezpečnou                     ač máš doma lás      ku  věč      nou

    D           /F#  G6    A7sus4  A7           D       /F#     G6       A7sus4  A7
2.    V kostech dobu předváleč     nou            cítíš při hře s touhle sle     čnou
    F#mi           Hmi7                         F#mi             Emi  A7sus2  A7
      dvoj má na tebe zbraň sečnou                umí být tečnou i  neteč     nou

    D        /F#   G6     A7sus4  A7            D         /F#   G6       A7sus4  A7
3.    Spát nemůžeš i když zí      váš             v duchu temný blues si zpí     váš
    F#mi           Emi                          F#mi         A67sus4  A7  A67      A7
    na minulost se v slzách díváš               co nenastalo mar      ně  skrý     váš

    D       /F#    G6    A7sus4  A7             D         /F#      G6    A7sus4  A7
4.    A tak pustíš svoje sklo    ny               k psaní jak v porcelán slo     ny
    F#mi            Hmi7                        F#mi          Emi    A7sus2    A7
      i kdybys uběh   maratony                    doběhnou tě stejně o         ny

Solo:
    Emi                       H9+               Emi                       D
𝅘𝅥𝅮   E  A  H  D  E±            H                 E  A  H  D  E  E±         D
    Emi                       H9+               Emi                       D
𝅘𝅥𝅮   E  A  H  D  E±            H                 E  A  H  D  E  E±         D

    Emi                       Hmi7              Emi         F#mi           A7sus4     A7
*.    Myslels jak jsi strašně vědomý              teď nevíš co je čisté    svědo      mí
    Emi                    Hmi7                 Ddim    (slide)                A7sus4   A7
      přátele máš a nejsou lakomý                 na rady sporný     nebo      pito     mý

I:
    D    /F#    G6    A7sus4  A7
    D    /F#    G6    A7sus4  A7
    D    /F#    G6    A7sus4  A7
    B6
    Cadd2

    D         /F#      G6     A7sus4  A7        D       /F#          G6   A7sus4  A7
6.    V změti pravd hledáš ty pra     vý          co je mužný, zralý a co zdra    vý
    F#mi                Hmi7                    Ddim    (slide)                  A7sus4      A7
      koho's nečekal se náhle staví               ty vzpomeneš si,               že tě život baví.

Outro:
    Bmaj         C9       D9   D
