Gándhí  (♡ 2016) - Život tě baví

Orig: D

I:
    A5(flag)
♪                   D  Cum  H  Aum  G  A                         G  F#um  G
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    B6                                          Cadd2                     C9   (slow)
♪                                                        F# F# F#   Eum   D  A#

    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D       /F#   G6     A7sus4                 D       /F#  G6   A7sus4
1.    Rum a sirup s fosforečnou                   dívku krajinově vděčnou
    F#mi               Emi                      F#mi         (slow) A67sus4  A7  A67    A7
      činí značně nebezpečnou                     ač máš doma       lás      ku  věč    nou

    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D           /F#  G6    A7sus4               D       /F#     G6       A7sus4
2.    V kostech dobu předválečnou                 cítíš při hře s touhle slečnou
    F#mi           Hmi7                         F#mi             Emi (slow) A7sus2  A7
      dvoj má na tebe zbraň sečnou                umí být tečnou i   ne     teč     nou

R:
    Emi                       Hmi7              Emi           F#mi         (slow)  A67       A7
      Myslels jak jsi strašně vědomý              teď nevíš   co je čisté          svě  do   mí
    Emi                    Hmi7                 Ddim    (slide)    (slow)        A67       A7
      přátele máš a nejsou lakomý            na rady sporný           a nebo     pi   to   mý

    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D        /F#   G6     A7sus4                D         /F#   G6       A7sus4
3.    Spát nemůžeš i když zíváš                   v duchu temný blues si zpíváš
    F#mi           Emi                          F#mi        (slow) A67sus4  A7  A67      A7
    na minulost se v slzách díváš               co nenastalo       mar      ně  skrý     váš

    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D       /F#    G6    A7sus4                 D         /F#      G6    A7sus4
4.    A tak pustíš svoje sklony                   k psaní jak v porcelán slony
    F#mi            Hmi7                        F#mi          Emi   (slow) A7sus2    A7
      i kdybys uběh   maratony                    doběhnou tě stejně       o         ny

Solo 2x:
    Emi                       H9+               Emi                       D
♪   E  A  H  D  E±     H                        E  A  H  D  E  E±     D

R:
    Emi                       Hmi7              Emi           F#mi         (slow)  A67       A7
      Myslels jak jsi strašně vědomý              teď nevíš   co je čisté          svě  do   mí
    Emi                    Hmi7                 Ddim    (slide)    (slow)        A67       A7
      přátele máš a nejsou lakomý            na rady sporný              nebo    pi   to   mý

I:
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    B6                                          Cadd2                     C9
♪                                                        F# F# F#   Eum   D  A#

    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D         /F#      G6     A7sus4            D       /F#          G6     A7sus4
6.    V změti pravd hledáš ty pravý               co je mužný, zralý   a co zdravý
    F#mi                Hmi7                    Ddim    (slide)      (slow)             A76  A7
      koho's nečekal se náhle staví          ty vzpomeneš si,               že tě život ba   ví.

Outro:
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    D      /F#      G6      A7sus4              D      /F#       G6       G  A7
    Bmaj            C6add2         D9           D                                   (slow)
    Bmaj            C9             Ami7         D                                          D5(flag)
♪                                                   D  Cum  H  Aum  G  A     G  F#um  G  A
